---
# Akeneo provisioning playbook
- name: Install Apache 2, PHP 5.6 and MySQL on akeneo nodes
  hosts: all
  sudo: yes
  gather_facts: true
  pre_tasks:
    - include: tasks/user.yml

  roles:
    - debops.ntp
    - geerlingguy.firewall
    - geerlingguy.apache
  tasks:
